name: Trigger-Localisation-Builds

on:
  workflow_dispatch:

jobs:

  Trigger-Localisation-Builds:
     name:
     runs-on: ubuntu-22.04
     steps:
      - name: Invoke workflow Brazilian in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-PT-BR
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Chinese in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-ZH
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Spain in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-ES
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow German in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-DE
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Italian in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-IT
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow French in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-FR
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Japanese in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-JA
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Russian in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-RU
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Korean in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-KO
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Polish in repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-PL
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
        continue-on-error: false                                                                         