on:
    pull_request:
        types: [ closed ]    
    workflow_dispatch:     
    schedule:
     - cron: '0 4 * * 1-5'   

env:
 RUNTIME_VERSION: "2023.1.0.${{ github.run_number }}"

jobs:

   RoboHelp:
     name: "RoboHelp"
     runs-on: windows-2019
     steps:
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - run: aws s3 cp ${{ secrets.S3_COMMAND }} ${{ secrets.ZIP_FILE }}
        shell: bash
      - name: Extract archive
        run: 7z x ${{ secrets.ZIP_FILE }}
        shell: bash
      - name: Enable git long paths to bypass path limit on Windows
        run: git config --system core.longpaths true
      - name: Check out the GMS2_Documentation repo
        uses: actions/checkout@v3
        with:
          path: Manual  
          token: ${{ secrets.GH_TOKEN }}
      - run: mkdir "%GITHUB_WORKSPACE%\YoYoStudioRoboHelp-${{ env.RUNTIME_VERSION }}"
        shell: cmd
      - run: | 
         RoboHelp.exe --cl "%GITHUB_WORKSPACE%\Manual\Manual\GMS2_Manual.rhpj" -o "GMS2 Manual Responsive HTML5" -p "%GITHUB_WORKSPACE%\YoYoStudioRoboHelp-${{ env.RUNTIME_VERSION }}" 
         7z a YoYoStudioRoboHelp-${{ env.RUNTIME_VERSION }}.zip "%GITHUB_WORKSPACE%\YoYoStudioRoboHelp-${{ env.RUNTIME_VERSION }}" -r
        shell: cmd
        working-directory: Adobe_RoboHelp_2020
      - name: Upload robohelp zip file
        uses: actions/upload-artifact@v2
        with:
           name: YoYoStudioRoboHelp
           path: YoYoStudioRoboHelp-${{ env.RUNTIME_VERSION }}.zip
           if-no-files-found: error
