name: Gdrive

on: [push]

jobs:

    build:        
      runs-on: ubuntu-latest
      steps:
       - run: |
           echo "Hello, world!" > myfile.txt
           7z a -tzip myarchive.zip myfile.txt
           rm myfile.txt     
           ls          
       - name: Upload to gdrive
         uses: agusprayogi02/auto-upload-gdrive@v1.0.1
         with:
           filename: ${{ github.workspace }}/myarchive.zip
           folderId: "1v3dkPTgtoJC96NOfFEyvpILkvzIXcng-"
           credentials: ${{ secrets.CREDENTIALS_JSON }}
           encoded: true
           mimeType: application/zip        