name: Gdrive

on: [push]

jobs:

    build:        
      runs-on: windows-2019
      steps:
       - run: |
           echo "Hello, world!" > myfile.txt
           7z a -tzip myarchive.zip myfile.txt
           rm myfile.txt     
           ls          
       - name: Upload a file to Google Drive
         uses: willo32/google-drive-upload-action@v1
         with:
            target: myarchive.zip
            credentials: ${{ secrets.CREDENTIALS_JSON }}
            parent_folder_id: "1v3dkPTgtoJC96NOfFEyvpILkvzIXcng-"