name: Gdrive

on: [push]

jobs:

    build:   
      
      runs-on: windows-2019
      env:
        LANGUAGE: ${{ vars.LANGUAGE }}
      steps:
       - run: |
           echo "Hello, world!" > myfile.txt
           zip myarchive.zip myfile.txt                
       - name: Upload a file to Google Drive
         uses: willo32/google-drive-upload-action@v1
         with:
            target: myarchive.zip
            credentials: ${{ secrets.CREDENTIALS_JSON }}
            parent_folder_id: "1v3dkPTgtoJC96NOfFEyvpILkvzIXcng-"